---
- name: "Installation Laptop"
  hosts: all

  roles:
    # ZSH
    - role: "zsh"
    - role: "bash"
    # UTILITIES
    - role: "utilities"
    # POWERSHELL
    - role: "powershell"
      vars:
        modules:
          - oh-my-posh
          - posh-git
        theme: paradox
    # GPG
    - role: "gpg"
      vars:
        default_key: "F2B6AEF1AA9B56B290C96AC07F9A9687E7CA0D86"
    # GIT
    - role: "git"
      vars:
        git_name: Thibault Serti
        git_email: "thibault.serti@gmail.com"
        signingkey: "F2B6AEF1AA9B56B290C96AC07F9A9687E7CA0D86"
    # DOCKER
    - role: "docker"
      become: true
      vars:
        docker_package: "{{ 'docker' if ansible_os_family == 'Archlinux' }}"
        docker_service_enabled: false
        docker_install_compose: false
        docker_users:
          - "{{ ansible_user_id }}"
    # SSH
    - role: "ssh"
      vars:
        copy_keys: true
    # MUTT
    - role: "neomutt"
    # TMUX
    - role: "tmux"
    # VIM
    - role: "vim"
    # ASDF
    - role: "asdf"
    # GUI
    - role: "gui"
    # VSCODE
    - role: "vscode"
      vars:
        extensions:
          # themes and icons
          - PKief.material-icon-theme
          - Perkovec.emoji
          # utils
          - GrapeCity.gc-excelviewer
          - tomoki1207.pdf
          - evilz.vscode-reveal
          - icrawl.discord-vscode
          - ms-vsliveshare.vsliveshare
          - ms-vsliveshare.vsliveshare-audio
          # Javascript and Typescript
          - dbaeumer.vscode-eslint
          - esbenp.prettier-vscode
          # Golang
          - golang.go
          # Git & Github
          - donjayamanne.githistory
          - eamodio.gitlens
          - GitHub.vscode-pull-request-github
          # Python
          - ms-python.python
          - ms-python.vscode-pylance
          - ms-toolsai.jupyter
          - njpwerner.autodocstring
          # Docker
          - ms-vscode-remote.remote-containers
          - ms-azuretools.vscode-docker
          # Bash
          - timonwong.shellcheck
          - foxundermoon.shell-format
          # C/C++
          - ms-vscode.cpptools
          # Powershell
          - ms-vscode.powershell
          # BDD SQL
          - mtxr.sqltools
          - mtxr.sqltools-driver-sqlite
          # Java
          - redhat.java
          # YAML, JSON, XML
          - redhat.vscode-commons
          - redhat.vscode-xml
          - redhat.vscode-yaml
          - samuelcolvin.jinjahtml
          # Ansible
          - zbr.vscode-ansible
          # Kubernetes
          - ms-kubernetes-tools.vscode-kubernetes-tools
          # Terraform
          - hashicorp.terraform
