---
- name: "Installation"
  hosts: all

  roles:
    - role: "zsh"
      vars:
        theme: agnoster
    - role: "bash"
    - role: "git"
      vars:
        git_name: Thibault Serti
        git_email: "thibault.serti@gmail.com"
        signingkey: "F2B6AEF1AA9B56B290C96AC07F9A9687E7CA0D86"
    - role: "docker"
      become: true
      vars:
        docker_package: "{{ 'docker' if ansible_os_family == 'Archlinux' }}"
        docker_service_enabled: false
        docker_install_compose: false
        docker_users:
          - "{{ ansible_user_id }}"
      tags:
        - notest