---
- name: Install zsh
  package:
    name:
      - zsh
    state: present

- name: Check for oh-my-zsh installation
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_stat

- name: Install curl
  package:
    name:
      - curl
    state: present
  when: not oh_my_zsh_stat.stat.exists

- name: Install oh-my-zsh
  raw: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists
