---
zsh_user_dir: "{{ ansible_user_dir }}"
zsh_user_id: "{{ ansible_user_id }}"
zsh_user_group: "{{ ansible_user_id }}"

zsh_dir: .zsh

plugins:
  - encode64
  - sudo
  - z

custom_plugins:
  - name: zsh-syntax-highlighting
    url: https://github.com/zsh-users/zsh-syntax-highlighting
  - name: zsh-autosuggestions
    url: https://github.com/zsh-users/zsh-autosuggestions

theme: "agnoster"

package_font: "{{ 'fonts-powerline' if ansible_os_family == 'Debian' else 'powerline-fonts' }}"