---
zsh_user_dir: "{{ ansible_user_dir }}"
zsh_user_id: "{{ ansible_user_id }}"
zsh_user_group: "{{ ansible_user_id }}"

zsh_dir: .zsh

plugins:
  - alias-tips
  - encode64
  - sudo
  - web-search
  - z
  - zsh-syntax-highlighting
  - zsh-autosuggestions

theme: "agnoster"
