---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update cache
      raw: apt update

      changed_when: false
    - name: Install sudo
      raw: test -e /usr/bin/sudo || (apt install -y sudo)
      changed_when: false

    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (apt install -y python3)
      become: true
      changed_when: false

    - name: Install usefull packages for testing
      package:
        name:
          - git
          - binutils
          - make
          - gcc
          - pkg-config
          - fakeroot
        state: present
      become: true
