---
- name: Write .gitconfig config
  template:
    src: gitconfig.j2
    dest: "{{ user_dir }}/.gitconfig"
    owner: "{{ user_id }}"
    group: "{{ user_group }}"
    mode: 0640

- name: Check for zsh installation
  stat:
    path: ~/.zsh
  register: zsh_stat

- name: Install zsh plugin
  template:
    src: git.zsh.j2
    dest: "{{ user_dir }}/.zsh/git.zsh"
    owner: "{{ user_id }}"
    group: "{{ user_group }}"
    mode: 0640
  when: zsh_stat.stat.exists