- name: Install fonts (Archlinux)
  package:
    name:
      - ttf-fira-code
      - nerd-fonts-noto-mono
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
    state: present
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Install fonts (Debian)
  package:
    name:
      - fonts-firacode
      - fonts-noto
      - fonts-noto-emoji
      - fonts-noto-cjk
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Install fonts (Fedora)
  package:
    name:
      - fira-code-fonts
      - google-noto-fonts-default
      - google-noto-emoji-fonts
      - google-noto-cjk-fonts
    state: present
  become: true
  when: ansible_os_family == 'RedHat'