---
# tasks file for shell-common

- name: Create {{ shell_dir }}
  file:
    path: "{{ shell_user_dir }}/{{ shell_dir }}/"
    state: directory
    mode: 0750

- name: Create {{ shell_dir }}/custom
  file:
    path: "{{ shell_user_dir }}/{{ shell_dir }}/custom/"
    state: directory
    mode: 0750

- name: Write env.sh
  copy:
    src: env.sh
    dest: "{{ shell_user_dir }}/{{ shell_dir }}/env.sh"
    owner: "{{ shell_user_id }}"
    group: "{{ shell_user_group }}"
    mode: 0640

- name: Write functions.sh
  copy:
    src: functions.sh
    dest: "{{ shell_user_dir }}/{{ shell_dir }}/functions.sh"
    owner: "{{ shell_user_id }}"
    group: "{{ shell_user_group }}"
    mode: 0640

- name: Write aliases.sh
  copy:
    src: aliases.sh
    dest: "{{ shell_user_dir }}/{{ shell_dir }}/aliases.sh"
    owner: "{{ shell_user_id }}"
    group: "{{ shell_user_group }}"
    mode: 0640
