---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
provisioner:
  name: ansible
verifier:
  name: ansible
