---
# defaults file for vscode

vscode_user_dir: "{{ ansible_user_dir }}"
vscode_user_id: "{{ ansible_user_id }}"
vscode_user_group: "{{ ansible_user_id }}"

extensions:
  # themes and icons
  - PKief.material-icon-theme
  - Perkovec.emoji
  # utils
  - CoenraadS.bracket-pair-colorizer
  - GrapeCity.gc-excelviewer
  - tomoki1207.pdf
  - evilz.vscode-reveal
  - icrawl.discord-vscode
  - ms-vsliveshare.vsliveshare
  - ms-vsliveshare.vsliveshare-audio
  # Javascript and Typescript
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  # Golang
  - golang.go
  # Git & Github
  - donjayamanne.githistory
  - eamodio.gitlens
  - GitHub.vscode-pull-request-github
  # Python
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - njpwerner.autodocstring
  # Docker
  - ms-vscode-remote.remote-containers
  - ms-azuretools.vscode-docker
  # Bash
  - timonwong.shellcheck
  - foxundermoon.shell-format
  # C/C++
  - ms-vscode.cpptools
  # Powershell
  - ms-vscode.powershell
  # BDD SQL
  - mtxr.sqltools
  - mtxr.sqltools-driver-sqlite
  # Java
  - redhat.java
  # YAML, JSON, XML
  - redhat.vscode-commons
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - samuelcolvin.jinjahtml
  # Ansible
  - zbr.vscode-ansible
  # Kubernetes
  - ms-kubernetes-tools.vscode-kubernetes-tools
  # Terraform
  - hashicorp.terraform
