---
# tasks file for vim

- name: Install prequisites (Archlinux)
  package:
    name:
      - python
      - python-pip
      - python-virtualenv
      - which
      - ruby
    state: present
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Install prequisites (Debian)
  package:
    name:
      - python3
      - python3-pip
      - python3-venv
      - ruby
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Install prequisites (Fedora)
  package:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
      - which
      - ruby
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install vim and neovim
  package:
    name:
      - vim
      - neovim
    state: present
  become: true

- name: Create .config custom dir
  file:
    path: "{{ vim_user_dir }}/.config"
    state: directory
    mode: 0750

- name: Install vim config from github
  ansible.builtin.git:
    repo: "https://github.com/rafi/vim-config.git"
    dest: "{{ vim_user_dir }}/.config/nvim"
    version: master

- name: Create symlink
  file:
    src: "{{ vim_user_dir }}/.config/nvim"
    dest: "{{ vim_user_dir }}/.vim"
    owner: "{{ vim_user_id }}"
    group: "{{ vim_user_group }}"
    state: link

- name: Install python modules
  pip:
    name:
      - pynvim
      - vim-vint
      - pycodestyle
      - pyflakes
      - flake8
    executable: pip3
    extra_args: --user
    state: present
  changed_when: false

- name: Install plugins
  community.general.make:
    chdir: "{{ vim_user_dir }}/.config/nvim"
    target: install
  changed_when: false

- name: Copy vimrc
  copy:
    src: vimrc.vim
    dest: "{{ vim_user_dir }}/.vimrc"
    owner: "{{ vim_user_id }}"
    group: "{{ vim_user_group }}"
    mode: 0640

- name: Copy local vim
  copy:
    src: local.vim
    dest: "{{ vim_user_dir }}/.config/nvim/config/local.vim"
    owner: "{{ vim_user_id }}"
    group: "{{ vim_user_group }}"
    mode: 0640
