---
# defaults file for utilities

packages:
  - bat
  - htop
  - inxi
  - ipcalc
  - jq
  - kdeconnect
  - less
  - lsb-release
  - ncdu
  - neofetch
  - net-tools
  - nmap
  - os-prober
  - powertop
  - prettyping
  - pwgen
  - ranger
  - smartmontools
  - time
  - tldr
  - traceroute
  - tree
  - wget
  - whois
  - xclip
  - youtube-dl

packages_arch:
  - lsd

packages_deb:
  - https://github.com/Peltoche/lsd/releases/download/0.21.0/lsd_0.21.0_amd64.deb
