name: Molecule utilities

on:
  push:
    branches:
      - main
    paths:
      - "roles/utilities/**"
  pull_request:
    branches:
      - main
    paths:
      - "roles/utilities/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scenario:
          - utilities-archlinux
          - utilities-fedora
          - utilities-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.17
        with:
          options: parallel
          scenario: "${{ matrix.scenario }}"